INSERT OR REPLACE INTO participants(id,name,gender,username,password_salt,password_hash,password_iterations,assigned_to,drawn) VALUES
(1,'Maurien Ruiz Borja','F','Maurien','','',0,NULL,0),
(2,'Mario Pastor Verbel','M','Mario','','',0,NULL,0),
(3,'Andrea Tuiran Mendez','F','Andrea','','',0,NULL,0),
(4,'Remberto Oviedo Contreras','M','Remberto','','',0,NULL,0),
(5,'Liover Campo Salcedo','M','Liover','','',0,NULL,0),
(6,'Gilma Barragan Acuña','F','Gilma','','',0,NULL,0),
(7,'Yuris Carpintero Polanco','F','Yuris','','',0,NULL,0),
(8,'Marco Fernandez Martinez','M','Marco','','',0,NULL,0),
(9,'Gloria Vargas Ojeda','F','Gloria','','',0,NULL,0),
(10,'Camila Sanjuan Uparela','F','Camila','','',0,NULL,0),
(11,'Alejandro Rivero Carrascal','M','Alejandro','','',0,NULL,0),
(12,'Clara Romero Vergara','F','Clara','','',0,NULL,0),
(13,'Jesus Salcedo Martinez','M','Jesus','','',0,NULL,0),
(14,'Wendy Robles Robles','F','Wendy','','',0,NULL,0),
(15,'Saidith Garrido Teran','F','Saidith','','',0,NULL,0),
(16,'Alfredo Amaya Lopez','M','Alfredo','','',0,NULL,0),
(17,'Carlos Martinez Jaraba','M','Carlos','','',0,NULL,0),
(18,'Martha Mier Thorrens','F','Martha','','',0,NULL,0),
(19,'Liseth Chamorro Avila','F','Liseth','','',0,NULL,0),
(20,'Ingris Cuello Marquez','F','Ingris','','',0,NULL,0),
(21,'Daniela Garcia Fernandez','F','Daniela','','',0,NULL,0),
(22,'Angel Oquendo','M','Angel','','',0,NULL,0),
(23,'Viviana Villar','F','Viviana','','',0,NULL,0),
(24,'Maria Victoria Arroyo','F','Maria','','',0,NULL,0);