const enc=new TextEncoder();
const b64u=b=>btoa(String.fromCharCode(...new Uint8Array(b))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
const fromB64u=s=>Uint8Array.from(atob(s.replace(/-/g,'+').replace(/_/g,'/')+'==='.slice((s.length+3)%4)),c=>c.charCodeAt(0));
async function verifyPassword(password,salt,stored,iterations){const key=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt:fromB64u(salt),iterations,hash:'SHA-256'},key,256);return b64u(bits)===stored}
async function sign(payload,secret){const key=await crypto.subtle.importKey('raw',enc.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return b64u(await crypto.subtle.sign('HMAC',key,enc.encode(payload)))}
async function session(payload,secret){return payload+'.'+await sign(payload,secret)}
async function auth(request,env){const c=request.headers.get('Cookie')||'';const m=c.match(/session=([^;]+)/);if(!m)return null;const [p,s]=m[1].split('.');if(!p||!s||s!==(await sign(p,env.SESSION_SECRET)))return null;const [id,role,exp]=p.split('|');if(Number(exp)<Date.now())return null;return {id:Number(id),role}}
function json(data,status=200,headers={}){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json',...headers}})}
async function assignment(db){const people=await db.prepare('SELECT id,name,gender FROM participants ORDER BY id').all();const a=people.results;const males=a.filter(x=>x.gender==='M'), females=a.filter(x=>x.gender==='F');const map=new Map();let available=females.slice().sort(()=>Math.random()-.5);for(const m of males){const t=available.pop();map.set(m.id,t.id)}let g=females.slice();let recipients=a.filter(x=>!Array.from(map.values()).includes(x.id));function solve(i,rec){if(i===g.length)return true;const giver=g[i];const choices=rec.slice().sort(()=>Math.random()-.5);for(const t of choices){if(t.id===giver.id)continue;map.set(giver.id,t.id);if(solve(i+1,rec.filter(x=>x.id!==t.id)))return true;map.delete(giver.id)}return false}if(!solve(0,recipients))throw new Error('No se pudo generar una asignación válida');return map}
async function draw(env,user){const p=await env.DB.prepare('SELECT id,name,gender,drawn,assigned_to FROM participants WHERE id=?').bind(user.id).first();if(!p)return json({error:'Usuario no encontrado'},404);if(p.drawn)return json({error:'Ya realizaste tu tiro',name:p.name,assignedTo:p.assigned_to},409);const target=await env.DB.prepare('SELECT id,name FROM participants WHERE id=?').bind(p.assigned_to).first();await env.DB.prepare('UPDATE participants SET drawn=1 WHERE id=? AND drawn=0').bind(p.id).run();return json({name:p.name,target:target?.name||null})}
export default {async fetch(request,env){const url=new URL(request.url);try{if(url.pathname==='/api/login'&&request.method==='POST'){const {username,password}=await request.json();if(username==='Admin'){const a=await env.DB.prepare('SELECT * FROM admins WHERE username=?').bind(username).first();if(!a||!(await verifyPassword(password,a.password_salt,a.password_hash,a.password_iterations)))return json({error:'Credenciales incorrectas'},401);const token=await session(`1|admin|${Date.now()+86400000}`,env.SESSION_SECRET);return json({role:'admin'},{headers:{'Set-Cookie':`session=${token}; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=86400`}})}const p=await env.DB.prepare('SELECT * FROM participants WHERE username=?').bind(username).first();if(!p||!(await verifyPassword(password,p.password_salt,p.password_hash,p.password_iterations)))return json({error:'Credenciales incorrectas'},401);const token=await session(`${p.id}|participant|${Date.now()+86400000}`,env.SESSION_SECRET);return json({role:'participant'},{headers:{'Set-Cookie':`session=${token}; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=86400`}})}
if(url.pathname==='/api/logout'){return new Response(null,{status:204,headers:{'Set-Cookie':'session=; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=0'}})}
const user=await auth(request,env);if(url.pathname==='/api/me'){if(!user)return json({authenticated:false},401);if(user.role==='admin')return json({authenticated:true,role:'admin'});const p=await env.DB.prepare('SELECT id,name,drawn FROM participants WHERE id=?').bind(user.id).first();return json({authenticated:true,role:'participant',participant:p})}if(!user)return json({error:'No autorizado'},401);
if(url.pathname==='/api/draw'&&request.method==='POST'){if(user.role!=='participant')return json({error:'No autorizado'},403);return draw(env,user)}
if(url.pathname==='/api/admin'&&user.role==='admin'){const rows=await env.DB.prepare('SELECT p.id,p.name,p.gender,p.username,p.drawn,t.name AS target FROM participants p LEFT JOIN participants t ON p.assigned_to=t.id ORDER BY p.id').all();return json({participants:rows.results})}
if(url.pathname==='/api/admin/reset'&&request.method==='POST'&&user.role==='admin'){const map=await assignment(env.DB);const stmts=[];for(const [giver,target] of map)stmts.push(env.DB.prepare('UPDATE participants SET assigned_to=?,drawn=0 WHERE id=?').bind(target,giver));await env.DB.batch(stmts);return json({ok:true})}
if(url.pathname==='/api/admin/edit'&&request.method==='POST'&&user.role==='admin'){const b=await request.json();if(!b.id||!b.name||!['M','F'].includes(b.gender))return json({error:'Datos inválidos'},400);await env.DB.prepare('UPDATE participants SET name=?,gender=? WHERE id=?').bind(b.name.trim(),b.gender,b.id).run();return json({ok:true})}
return env.ASSETS.fetch(request)}catch(e){return json({error:'Error interno',detail:e.message},500)}}};
